/* Generated by serverless-leo */
import { ConfigurationBuilder } from "leo-sdk/lib/configuration-builder";
import { MySqlData } from "types";

export interface ProjectConfigNew {
	item: {
		endpoint: string;
	};
	mysqlPortRegion: number;
	mysqlPortRegion2: number;
	mysqlPort: number;
	mysqlPassword: string;
	mysql: MySqlData;
	redshifturl: string;
	defaultNumRetries: number;
	weather: {
		inner: string;
		inner3: string;
	};
}

export default new ConfigurationBuilder<ProjectConfigNew>(process.env.RSF_CONFIG).build({});