Resources:
  BotRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            AWS:
              Fn::Sub: arn:aws:iam::${AWS::AccountId}:root
            Service:
            - lambda.amazonaws.com
        Version: '2012-10-17'
      # Policies:
      #   - PolicyName: RStreamsBusSecret
      #     PolicyDocument:
      #       Version: '2012-10-17'
      #       Statement:
      #         - Effect: Allow
      #           Action: secretsmanager:GetSecretValue
      #           Resource: 
      #             Fn::Sub: arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:rstreams-${RStreamsBus}-*
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      # - Fn::ImportValue: 
      #     Fn::Sub: ${RStreamsBus}-Policy
